# Generated by Django 3.2.2 on 2021-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_brands_contactmessage_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='comment',
            field=models.CharField(blank=True, default='Thumbs up prodigious store', max_length=250, null=True),
        ),
    ]
