# Generated by Django 3.2.2 on 2021-05-20 09:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_setting_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='banner_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='what we do'),
        ),
    ]
