# Generated by Django 3.2.2 on 2021-05-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'verbose_name': 'Userprofile', 'verbose_name_plural': 'Userprofile(s)'},
        ),
    ]
