# Generated by Django 3.2.2 on 2021-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
